export interface Dish {
    idMeal: string,
    strMeal: string,
    strCategory: string,
    strArea: string,
    strInstructions: string,
    strMealThumb: string,
    strTags?: string,
    strYoutube: string,
    strIngredient1: string | unknown,
    strIngredient2: string | unknown,
    strIngredient3: string | unknown,
    strIngredient4: string | unknown,
    strIngredient5: string | unknown,
    strIngredient6: string | unknown,
    strIngredient7: string | unknown,
    strIngredient8: string | unknown,
    strIngredient9: string | unknown,
    strIngredient10: string | unknown,
    strIngredient11: string | unknown,
    strIngredient12: string | unknown,
    strIngredient13: string | unknown,
    strIngredient14: string | unknown,
    strIngredient15: string | unknown,
    strIngredient16: string | unknown,
    strIngredient17: string | unknown,
    strIngredient18: string | unknown,
    strIngredient19: string | unknown,
    strIngredient20: string | unknown,
    strMeasure1: string | unknown,
    strMeasure2: string | unknown,
    strMeasure3: string | unknown,
    strMeasure4: string | unknown,
    strMeasure5: string | unknown,
    strMeasure6: string | unknown,
    strMeasure7: string | unknown,
    strMeasure8: string | unknown,
    strMeasure9: string | unknown,
    strMeasure10: string | unknown,
    strMeasure11: string | unknown,
    strMeasure12: string | unknown,
    strMeasure13: string | unknown,
    strMeasure14: string | unknown,
    strMeasure15: string | unknown,
    strMeasure16: string | unknown,
    strMeasure17: string | unknown,
    strMeasure18: string | unknown,
    strMeasure19: string | unknown,
    strMeasure20: string | unknown,
}